# Generated by Django 3.1.4 on 2020-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('ingredients', models.CharField(max_length=400, verbose_name='食材')),
                ('picture', models.FileField(upload_to='', verbose_name='图片')),
                ('difficulty', models.CharField(choices=[('Easy', '容易'), ('Medium', '中等'), ('Hard', '困难')], max_length=10, verbose_name='制作难度')),
                ('prep_time', models.PositiveIntegerField(verbose_name='准备时间')),
                ('prep_guide', models.TextField(verbose_name='制作指南')),
            ],
            options={
                'verbose_name': '食谱',
                'verbose_name_plural': '食谱',
            },
        ),
    ]
