# Generated by Django 3.1.4 on 2020-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('simple_intro', models.TextField(verbose_name='简单介绍')),
                ('food_type', models.CharField(choices=[('Meat', '肉类'), ('Beans', '豆类'), ('Aquatic_products', '水产品'), ('Dairy_products', '乳制品'), ('Beverage', '饮品'), ('Fruit_vegetable', '果蔬')], max_length=20, verbose_name='食品类型')),
                ('calorie', models.FloatField(verbose_name='卡路里')),
                ('carbohydrate', models.FloatField(verbose_name='碳水化合物')),
                ('fat', models.FloatField(verbose_name='脂肪')),
                ('protein', models.FloatField(verbose_name='蛋白质')),
                ('cellulose', models.FloatField(verbose_name='纤维素')),
                ('picture', models.FileField(upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '食品',
                'verbose_name_plural': '食品',
            },
        ),
    ]
