# Generated by Django 3.1.4 on 2020-12-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('picture', models.FileField(upload_to='', verbose_name='图片')),
                ('article_content', models.TextField(verbose_name='正文')),
            ],
        ),
    ]
