# Generated by Django 3.1.4 on 2020-12-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201214_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='introduction',
            field=models.CharField(default=1234, max_length=120, verbose_name='一句话介绍'),
            preserve_default=False,
        ),
    ]
