# Generated by Django 3.1.4 on 2020-12-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_diary_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('Meat', '肉类'), ('Beans', '豆类'), ('Aquatic_products', '水产品'), ('Dairy_products', '乳制品'), ('Beverage', '饮品'), ('Fruit_vegetable', '果蔬'), ('Snacks', '零食'), ('Other', '其它')], max_length=20, verbose_name='食品类型'),
        ),
    ]
