# Generated by Django 3.1.4 on 2020-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201214_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='owner',
            field=models.CharField(default='abc', max_length=120, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.CharField(default='abc', max_length=120, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
