# Generated by Django 3.1.4 on 2020-12-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201220_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
